# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Open Web Calendar
# site url, see https://www.mkdocs.org/user-guide/configuration/#site_url
site_url: https://open-web-calendar.quelltext.eu
repo_url: https://github.com/niccokunzmann/open-web-calendar/
repo_name: niccokunzmann/open-web-calendar
edit_uri: blob/master/docs/
site_description: Embed a highly customizable web calendar into your website using ICal source links
copyright: "&copy; 2024 Nicco Kunzmann and Open Web Calendar Contributors"

theme:
  palette:
    # colors of the calendar
    # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    primary: black
    accent: yellow

    # Palette toggle for automatic mode
#     - media: "(prefers-color-scheme)"
#       toggle:
#         icon: material/brightness-auto
#         name: Switch to light mode
#
#     # Palette toggle for light mode
#     - scheme: default
#       toggle:
#         icon: material/brightness-7
# #        primary: black
# #        accent: yellow
#         name: Switch to dark mode
#         media: "(prefers-color-scheme: light)"
#
#     # Palette toggle for dark mode
#     - scheme: slate
#       toggle:
#         icon: material/brightness-4
# #        primary: black
# #        accent: yellow
#         name: Switch to system preference
#         media: "(prefers-color-scheme: dark)"

  # font, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Ubuntu
    code: Ubuntu Mono
  language: en
  # logo, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  logo: assets/img/logo/owc.svg
  favicon: assets/img/logo/owc.svg
  # instant loading, see https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - content.action.edit
  icon:
    edit: material/pencil
    view: material/eye
  # theme, see
  name: material
  custom_dir: docs/overrides
plugins:
  # privacy, see https://squidfunk.github.io/mkdocs-material/plugins/privacy/
  - privacy # asset filtering can be circumvented by html escaping the content
            # for l in b'https://giscus.app/client.js': print('&#' + hex(l)[1:]+';', end="")
#      assets_exclude: # see also https://github.com/giscus/giscus/issues/1348
#        - cdn.jsdelivr.net/npm/mathjax@3/*
#        - giscus.app/* # see https://squidfunk.github.io/mkdocs-material/plugins/privacy/#config.assets_exclude
  # offline, see https://squidfunk.github.io/mkdocs-material/plugins/offline/
#  - offline
  - social
  # blog, see https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
  - blog
#      authors_profiles: true # sponsors only
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      enabled: !ENV [CI, false]
#  - tags\
  # git revision, see https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-dates
  - git-revision-date-localized:
      enable_creation_date: true
  # markdownextradata, see https://github.com/rosscdh/mkdocs-markdownextradata-plugin
  - markdownextradata
  # macros, see https://mkdocs-macros-plugin.readthedocs.io/en/latest/macros/
  - macros
  # meta description, see https://github.com/prcr/mkdocs-meta-descriptions-plugin
  - meta-descriptions

extra: # language support, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/niccokunzmann/open-web-calendar/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/niccokunzmann/open-web-calendar
    - icon: fontawesome/brands/mastodon
      link: https://toot.wales/tags/OpenWebCalendar
      name: Nicco Kunzmann
    - icon: fontawesome/solid/paper-plane
      link: mailto:niccokunzmann@rambler.ru
  link:
    # do not use - but _
    web: https://open-web-calendar.hosted.quelltext.eu
    tor: https://tor.open-web-calendar.hosted.quelltext.eu
    repo: https://github.com/niccokunzmann/open-web-calendar/
    code: https://github.com/niccokunzmann/open-web-calendar/tree/master/
    issues: https://github.com/niccokunzmann/open-web-calendar/issues
    tags: https://github.com/niccokunzmann/open-web-calendar/tags
    weblate: https://hosted.weblate.org/engage/open-web-calendar/
    good_first_issue:  https://github.com/niccokunzmann/open-web-calendar/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
    dockerhub: https://hub.docker.com/r/niccokunzmann/open-web-calendar
    fund:
      polar: https://polar.sh/niccokunzmann/open-web-calendar
      open_collective: https://opencollective.com/open-web-calendar/
      github_sponsors: https://github.com/sponsors/niccokunzmann
    templates: https://open-web-calendar.quelltext.eu/assets/templates

# navigation, see https://www.mkdocs.org/user-guide/configuration/#nav
nav:
  - index.md
  - templates.md
  - contributing.md
  - blog/index.md
  - Hosting:
    - host/hosted.md
    - host/self.md
    - host/docker.md
  - Development:
    - dev/index.md
    - dev/api.md
    - dev/maintain.md
  - SECURITY.md
  - changelog.md
  - dunno.md

# validation, see https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

watch:
  - static/img/logo

markdown_extensions:
  - smarty # see https://python-markdown.github.io/extensions/smarty/
  - toc: # see https://python-markdown.github.io/extensions/toc/
      permalink: true
  - sane_lists # see https://python-markdown.github.io/extensions/sane_lists/
  - meta # see https://python-markdown.github.io/extensions/meta_data/
  - pymdownx.tabbed # see https://mrkeo.github.io/reference/content-tabs/
  - pymdownx.superfences # see https://mrkeo.github.io/reference/content-tabs/
  - pymdownx.highlight # see https://mrkeo.github.io/reference/code-blocks/
  - pymdownx.inlinehilite # see https://mrkeo.github.io/reference/code-blocks/#inlinehilite
  - pymdownx.details # see https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - abbr
  - pymdownx.snippets # see https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - attr_list # see https://mrkeo.github.io/reference/images/

extra_css:
  - css/code-blocks.css
extra_javascript:
  - js/popper.js
  - js/jquery-3.7.1.min.js
  - js/tippy.js
  - js/clipboard.min.js
  - js/code-blocks.js
