# SPDX-FileCopyrightText: 2024 Nicco Kunzmann and Open Web Calendar Contributors <https://open-web-calendar.quelltext.eu/>
#
# SPDX-License-Identifier: CC-BY-SA-4.0

# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Open Web Calendar
# site url, see https://www.mkdocs.org/user-guide/configuration/#site_url
site_url: https://open-web-calendar.quelltext.eu
repo_url: https://github.com/niccokunzmann/open-web-calendar/
repo_name: niccokunzmann/open-web-calendar
edit_uri: blob/master/docs/
site_description: Embed a highly customizable web calendar into your website using ICal source links
copyright: '<span xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://open-web-calendar.quelltext.eu/">Open Web Calendar Documentation</a> by <span property="cc:attributionName">Nicco Kunzmann and Open Web Calendar Contributors</span><br/> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Creative Commons Attribution-ShareAlike 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></span> '

theme:
  palette:
    # colors of the calendar
    # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    primary: black
    accent: yellow

    # Palette toggle for automatic mode
#     - media: "(prefers-color-scheme)"
#       toggle:
#         icon: material/brightness-auto
#         name: Switch to light mode
#
#     # Palette toggle for light mode
#     - scheme: default
#       toggle:
#         icon: material/brightness-7
# #        primary: black
# #        accent: yellow
#         name: Switch to dark mode
#         media: "(prefers-color-scheme: light)"
#
#     # Palette toggle for dark mode
#     - scheme: slate
#       toggle:
#         icon: material/brightness-4
# #        primary: black
# #        accent: yellow
#         name: Switch to system preference
#         media: "(prefers-color-scheme: dark)"

  # font, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Ubuntu
    code: Ubuntu Mono
  language: en
  # logo, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  logo: assets/img/logo/owc.svg
  favicon: assets/img/logo/owc.svg
  # instant loading, see https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
  features:
    # - navigation.instant
    # - navigation.instant.prefetch
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - content.action.edit
    - navigation.instant
#    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.tabs.link
  icon:
    edit: material/pencil
    view: material/eye
  # theme, see
  name: material
  custom_dir: docs/overrides

plugins:
  # privacy, see https://squidfunk.github.io/mkdocs-material/plugins/privacy/
  - privacy # asset filtering can be circumvented by html escaping the content
            # for l in b'https://giscus.app/client.js': print('&#' + hex(l)[1:]+';', end="")
#      assets_exclude: # see also https://github.com/giscus/giscus/issues/1348
#        - cdn.jsdelivr.net/npm/mathjax@3/*
#        - giscus.app/* # see https://squidfunk.github.io/mkdocs-material/plugins/privacy/#config.assets_exclude
  # offline, see https://squidfunk.github.io/mkdocs-material/plugins/offline/
#  - offline
  - social
  # blog, see https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
  # incompatible with translation by i18n
#  - blog
#      authors_profiles: true # sponsors only
  - rss:
      match_path: news/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
#  - tags\
  # markdownextradata, see https://github.com/rosscdh/mkdocs-markdownextradata-plugin
  - markdownextradata
  # macros, see https://mkdocs-macros-plugin.readthedocs.io/en/latest/macros/
  - macros
  # meta description, see https://github.com/prcr/mkdocs-meta-descriptions-plugin
  - meta-descriptions
  # - i18n:
  #     reconfigure_material: true
  #     languages:
  #       - locale: en
  #         name: English
  #         default: true
  #       - locale: de
  #         name: Deutsch
  #         nav_translations:
  #           Hosting: Aufsetzen
  #           Development: Entwicklung
  #           News: Neuigkeiten

  - mdpo:
      locale_dir: ../translations
      lc_messages: true # store all documentation translations separately
      languages:
        - pot # generate the template files
        - en
        - de
        - es
        - nb_NO
        - it
        - th
        - eo
        - hr
        - ko
        - ko_LAVA
        - sk
        - zh_Hant
# add mdpo.languages above
      translate:
        - site_name
        - site_description
#        - copyright
#      min_translated_messages: 50%
      exclude:
        - docs/changelog.md
        - docs/dev/translate.md
        - docs/dev/maintain.md
        - docs/dunno.md
        - docs/news/*

  # git revision, see https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-dates
#  - git-revision-date-localized:
#      enable_creation_date: true
# do not use the language selector
#  - material-relative-language-selector
  # snippets and exclude from https://pypi.org/project/mkdocs-snippets/
  - exclude:
      glob:
        - snippets/*
#  - snippets

extra: # language support, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/
  social:
    - icon: fontawesome/solid/globe
      link: https://open-web-calendar.hosted.quelltext.eu
    - icon: fontawesome/brands/github
      link: https://github.com/niccokunzmann/open-web-calendar/
      name: GitHub
    - icon: fontawesome/solid/language
      link: https://hosted.weblate.org/engage/open-web-calendar/
      name: Weblate
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/open-web-calendar/
      name: PyPI
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/niccokunzmann/open-web-calendar
      name: Docker
    - icon: fontawesome/brands/mastodon
      link: https://toot.wales/tags/OpenWebCalendar
      name: "Mastodon #OpenWebCalendar"
    - icon: fontawesome/solid/paper-plane
      link: mailto:niccokunzmann@rambler.ru
  link:
    # do not use - but _
    web: https://open-web-calendar.hosted.quelltext.eu
    tor: https://tor.open-web-calendar.hosted.quelltext.eu
    repo: https://github.com/niccokunzmann/open-web-calendar/
    code: https://github.com/niccokunzmann/open-web-calendar/tree/master/
    pypi: https://pypi.org/project/open-web-calendar/
    issues: https://github.com/niccokunzmann/open-web-calendar/issues
    tags: https://github.com/niccokunzmann/open-web-calendar/tags
    weblate: https://hosted.weblate.org/engage/open-web-calendar/
    good_first_issue:  https://github.com/niccokunzmann/open-web-calendar/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
    dockerhub: https://hub.docker.com/r/niccokunzmann/open-web-calendar
    fund:
      polar: https://polar.sh/niccokunzmann/open-web-calendar
      open_collective: https://opencollective.com/open-web-calendar/
      github_sponsors: https://github.com/sponsors/niccokunzmann
    templates: https://open-web-calendar.quelltext.eu/assets/templates

  # From https://pypi.org/project/mkdocs-mdpo-plugin/
  # note that longer language codes might need a mapping in
  #     docs/overrides/partials/languages
  # see also https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#custom-translations
  alternate:
    - name: English
      lang: en
    - name: Deutsch
      link: de
      lang: de
    - name: Español
      link: es
      lang: es
    - name: Norsk bokmål
      link: nb_NO
      lang: nb_NO
    - name: Italiano
      link: it
      lang: it
    - name: อังกฤษ
      link: th
      lang: th
    - name: Esperanto
      link: eo
      lang: eo
    - name: Hrvatski
      link: hr
      lang: hr
    - name: Slovenčina
      link: sk
      lang: sk
# add extra.alternate languages above
    - name: Translate
      link: https://hosted.weblate.org/engage/open-web-calendar/
      lang: en

# navigation, see https://www.mkdocs.org/user-guide/configuration/#nav
nav:
  - index.md
  - templates.md
  - contributing.md
  - News:
    - news/social-media.md
    - news/2024-04-10-website.md
  - Hosting:
    - host/hosted.md
    - host/self.md
    - host/docker.md
    - host/pypi.md
    - host/configure.md
    - host/migrate.md
  - Development:
    - dev/translate.md
    - dev/index.md
    - dev/api.md
    - dev/maintain.md
    - dev/license.md
  - SECURITY.md
  - changelog.md
  - host/privacy-policy.md
  - dunno.md

# validation, see https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: info
  unrecognized_links: info
  nav:
    omitted_files: warn
    not_found: warn
  links:
    absolute_links: warn
    unrecognized_links: warn
    not_found: warn

watch:
  - open_web_calendar/static/img/logo

markdown_extensions:
  - smarty # see https://python-markdown.github.io/extensions/smarty/
  - toc: # see https://python-markdown.github.io/extensions/toc/
      permalink: true
  - sane_lists # see https://python-markdown.github.io/extensions/sane_lists/
  - meta # see https://python-markdown.github.io/extensions/meta_data/
  - pymdownx.tabbed # see https://mrkeo.github.io/reference/content-tabs/
  - pymdownx.superfences # see https://mrkeo.github.io/reference/content-tabs/
  - pymdownx.highlight # see https://mrkeo.github.io/reference/code-blocks/
  - pymdownx.inlinehilite # see https://mrkeo.github.io/reference/code-blocks/#inlinehilite
  - pymdownx.details # see https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - abbr
  - pymdownx.snippets: # see https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
      base_path: ["docs/snippets", "docs/assets/templates"]
  - attr_list # see https://mrkeo.github.io/reference/images/
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.superfences
hooks:
  - docs/hooks/set_canonical_url.py
